// These styles apply to every route in the application
"use client"
import './globals.css'
import { Sidebar, Navbar } from 'flowbite-react';
import { NavLink } from 'react-router-dom'
import { HiChartPie, HiDatabase, HiUser, HiCog } from 'react-icons/hi';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{backgroundImage: 'url(bg.png)'}} className='bg-scroll bg-cover bg-center z-0'>
      <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
        <div className="relative flex h-screen flex-col justify-center overflow-hidden h-auto max-w-full py-6 sm:py-12">
         {/*} <img src="bg.png" alt="" className="absolute bg-cover min-w-full min-h-full" />
          
          <div className="absolute inset-0 bg-center"></div>
          {/* <Navbar fluid rounded>
                <Navbar.Brand>
                        <img
                            alt="Flowbite React Logo"
                            className="mr-3 h-6 sm:h-9"
                            src={"https://picsum.photos/100/100"}
                        />
                        <h1>TEST</h1>
                </Navbar.Brand>
                <div className="flex md:order-2">
                    <button>
                        Log Out
                    </button>
                    <Navbar.Toggle />
                </div>
            </Navbar>
          <Sidebar aria-label="Sidebar with multi-level dropdown example">
            <Sidebar.Items>
              <Sidebar.ItemGroup>
                <Sidebar.Item
                  href="/dashboard"
                  icon={HiChartPie}
                >
                  <p>
                    Dashboard
                  </p>
                </Sidebar.Item>
                <Sidebar.Item
                  href="/question"
                  icon={HiDatabase}
                >
                  <p>
                    Preview Question
                  </p>
                </Sidebar.Item>

                <div>
                  <Sidebar.Collapse
                    icon={HiUser}
                    label="Admin"
                  >
                    <Sidebar.Item href="/users">
                      Users
                    </Sidebar.Item>
                    <Sidebar.Item href="/roles">
                      Role
                    </Sidebar.Item>
                  </Sidebar.Collapse>
                </div>

                <Sidebar.Collapse
                  icon={HiCog}
                  label="Settings"
                >
                  <Sidebar.Item >
                    <button>
                      Log out
                    </button>
                  </Sidebar.Item>
                </Sidebar.Collapse>
              </Sidebar.ItemGroup>
            </Sidebar.Items>
          </Sidebar> */}
          <div className='flex items-center justify-center h-screen'>
            <div className='px-2'>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}